# Generated by Django 2.2.1 on 2019-05-30 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=30)),
                ('duration_in_month', models.SmallIntegerField()),
                ('courseNumber', models.CharField(max_length=10)),
                ('course_description', models.TextField(max_length=100)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teacher.Teacher')),
            ],
        ),
    ]
